name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt || true
          # Optional dependencies used in code paths
          pip install pyyaml || true

      - name: Lint (flake8)
        run: |
          flake8 || true

      - name: Format check (black)
        run: |
          black --check . || true

      - name: Type check (mypy)
        run: |
          mypy . || true

      - name: Run tests (pytest)
        run: |
          pytest -q

